- README.md
- molgenis-app-vibe/src/test/resources/vibe.html
> README fix & update homepage to actual.

- molgenis-app-vibe/src/test/resources/vibe.html
> Minor adjustments

- molgenis-app-vibe/src/test/resources/vibe.html
> Fix for table creation being triggered too soon.

- Jenkinsfile
- molgenis-app-vibe/pom.xml
- pom.xml
> Release fixes

- Jenkinsfile
> Fixed coverage being sent wrongly to sonarcloud.

- molgenis-app-vibe/src/test/resources/vibe.html
- [N.A.] Documentation was updated
After merge:
> Explicit feedback when no results were found.

- Jenkinsfile
- Removed line causing Jenkins to fail.
- Adjusted artifactIds in Jenkinsfile.
Before merge:
After merge:
> Jenkins fixes

- Jenkinsfile
- molgenis-app-vibe/pom.xml
- pom.xml
> More Jenkins fixes.

- molgenis-app-vibe/pom.xml
- molgenis-app-vibe/src/main/java/org/molgenis/vibe/VibeServiceImpl.java
- molgenis-app-vibe/src/main/resources/molgenis-app-vibe.properties
- pom.xml
- Integrated #21.
- Updated to vibe version using HDT instead of TDB.
- Method 3 of #15 tested works. Method 2 might not work as expected (which output is actually shown though no error is caused anymore), but this would require the user to adjust the front-end code anyway.
- [n.a.] Documentation was updated
After merge:
> Tdb to hdt

- README.md
- molgenis-app-vibe/src/main/java/org/molgenis/vibe/VibeConfig.java
- molgenis-app-vibe/src/main/java/org/molgenis/vibe/VibeDatabaseClient.java
- molgenis-app-vibe/src/main/java/org/molgenis/vibe/VibeService.java
- molgenis-app-vibe/src/main/java/org/molgenis/vibe/VibeServiceImpl.java
> Vibe database is now loaded within the config instead of each service call.

- molgenis-app-vibe/Dockerfile
- molgenis-app-vibe/docker-compose.yml
> chore: download vibe data to docker container

- README.md
> docs: update readme to explain how to run with docker

- molgenis-app-vibe/src/main/resources/css/vibe.css
- molgenis-app-vibe/src/test/resources/vibe.html
Some examples to test the front-end (after the html file has been updated):
- When clicking "Execute" without any input, an error should be shown indicating an empty string was given.
- [this localhost URL](http://localhost:8080/menu/main/home?phenotypes=%20%20%20%20%20%20,) the error should indicate it got 2 empty strings.
- [this localhost URL](http://localhost:8080/menu/main/home?phenotypes=HP:1234567,HP:1234,HP:12345678,%20%20%20%20%20%20HP:1234567%20%20%20%20%20%20,1234567,HP:) the error should indicate all items except the 1st & 4th are invalid.
- [this localhost URL](http://localhost:8080/menu/main/home?phenotypes=HP:0002996,%20%20%20%20%20%20HP:0002997%20%20%20%20%20%20) should succeed.
Before merge
After merge:
> Frontend input validation

- README.md
> Added workaround for #29 in README

- molgenis-app-vibe/pom.xml
- [N.A.] Documentation was updated
After merge:
> Updated vibe dependency.

- README.md
- [N.A.] Functionality works & meets specs
After merge:
- [N.A.] Added feature/fix to draft release notes
> Removed obsolete info from README.

- molgenis-app-vibe/pom.xml
> Bump vibe.version to 5.1.4 and vibe-hdt.version to 5.1.0

- molgenis-app-vibe/pom.xml
- pom.xml
- [N.A.] Functionality works & meets specs
- [N.A.] Documentation was updated
After merge:
- [N.A.] Added feature/fix to draft release notes
> Version bump.

- Jenkinsfile
So that multiple-digit versions are supported.
After merge:
> Fix Jenkinsfile expected branch name

- molgenis-app-vibe/pom.xml
- pom.xml
> Bump version to 8.1.8-VIBE-1.3.0-SNAPSHOT

- Jenkinsfile
> Increased time to respond in Jenkins file equal to VIBE repository.

- molgenis-app-vibe/pom.xml
- pom.xml
build(deps): bump aws-java-sdk-s3 from 1.11.86 to 1.12.261
build(deps): bump poi from 4.0.1 to 4.1.1
build(deps): bump zip4j from 1.3.2 to 2.10.0
vibe version bump from 5.2.0 to 5.3.0
version bump
- Implemented feature [...]
- Fixed bug [...]
Additional information about made changes, known issues, etc.
Please update the checklists when steps are completed.
> build(deps): bump aws-java-sdk-s3, poi, zip4j

- molgenis-app-vibe/src/test/resources/vibe.html
- Implemented feature [...]
- Fixed bug [...]
Additional information about made changes, known issues, etc.
Please update the checklists when steps are completed.
> Updated vibe version in HTML.

- molgenis-app-vibe/pom.xml
- pom.xml
build(deps): bump spring-boot-starter-parent from 2.1.3.RELEASE to 2.1.18.RELEASE (fix)
- Implemented feature [...]
- Fixed bug [...]
Additional information about made changes, known issues, etc.
Please update the checklists when steps are completed.
> build(deps): bump poi from 4.0.1 to 4.1.1 (fix)

- molgenis-app-vibe/pom.xml
- Implemented feature [...]
- Fixed bug [...]
Additional information about made changes, known issues, etc.
Please update the checklists when steps are completed.
> fix(deps): bump dependency-check-maven from 3.1.2 to 7.3.0
